/**
 * MongoDB Data Verification Script
 * 
 * This script helps you check:
 * 1. All user data in MongoDB
 * 2. Feature vectors generated by ML model
 * 3. Matching results for specific users
 * 4. Data quality and completeness
 */

const mongoose = require('mongoose');
const RoommateMatcher = require('./RoommateMatcher');
const UserDetails = require('../models/UserDetails');
require('dotenv').config();

async function checkMongoData() {
  try {
    console.log('🔍 Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB\n');

    // 1. Check total users in database
    const totalUsers = await UserDetails.countDocuments();
    console.log(`📊 Total Users in Database: ${totalUsers}\n`);

    // 2. Display all users with key ML fields
    console.log('👥 All Users with ML Features:');
    console.log('=' .repeat(80));
    
    const users = await UserDetails.find({}).select('fullName age budgetRange sleepSchedule smoking drinking cleanlinessLevel studyStyle introvertExtrovert');
    
    users.forEach((user, index) => {
      console.log(`${index + 1}. ${user.fullName}`);
      console.log(`   ID: ${user._id}`);
      console.log(`   Age: ${user.age} | Budget: ${user.budgetRange} | Sleep: ${user.sleepSchedule}`);
      console.log(`   Smoking: ${user.smoking} | Drinking: ${user.drinking} | Cleanliness: ${user.cleanlinessLevel}`);
      console.log(`   Study Style: ${user.studyStyle} | Introvert: ${user.introvertExtrovert}/5`);
      console.log('');
    });

    // 3. Initialize ML model and check feature vectors
    console.log('🧠 ML Model Feature Vectors:');
    console.log('=' .repeat(80));
    
    const matcher = new RoommateMatcher();
    await matcher.trainModel(users);

    console.log(`Model trained with ${matcher.userVectors.size} users\n`);

    // 4. Display feature vectors for each user
    matcher.userVectors.forEach((vector, userId) => {
      const userData = matcher.userData.get(userId);
      console.log(`${userData.name} (ID: ${userId})`);
      console.log(`Feature Vector: [${vector.map(v => v.toFixed(3)).join(', ')}]`);
      console.log('');
    });

    // 5. Test matching for each user
    console.log('💝 Matching Results:');
    console.log('=' .repeat(80));
    
    for (const [userId, userData] of matcher.userData) {
      try {
        const matches = matcher.findMatches(userId, 3);
        console.log(`Top 3 matches for ${userData.name}:`);
        matches.forEach((match, index) => {
          console.log(`  ${index + 1}. ${match.name} - ${match.matchPercentage}%`);
        });
        console.log('');
      } catch (error) {
        console.log(`Error finding matches for ${userData.name}: ${error.message}`);
      }
    }

    // 6. Data quality check
    console.log('🔍 Data Quality Check:');
    console.log('=' .repeat(80));
    
    let issues = [];
    
    users.forEach(user => {
      // Check for missing required fields
      if (!user.age || user.age < 16 || user.age > 30) {
        issues.push(`${user.fullName}: Invalid age (${user.age})`);
      }
      if (!user.introvertExtrovert || user.introvertExtrovert < 1 || user.introvertExtrovert > 5) {
        issues.push(`${user.fullName}: Invalid introvertExtrovert (${user.introvertExtrovert})`);
      }
    });

    if (issues.length === 0) {
      console.log('✅ All data quality checks passed!');
    } else {
      console.log('⚠️ Data Quality Issues:');
      issues.forEach(issue => console.log(`   - ${issue}`));
    }

    console.log('\n🎉 Data verification complete!');

  } catch (error) {
    console.error('❌ Error checking data:', error);
  } finally {
    await mongoose.connection.close();
  }
}

// Quick check function
async function quickCheck() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    
    const users = await UserDetails.find({}).select('fullName age budgetRange sleepSchedule');
    console.log(`📊 Found ${users.length} users in MongoDB:`);
    
    users.forEach((user, index) => {
      console.log(`${index + 1}. ${user.fullName} (Age: ${user.age}, Budget: ${user.budgetRange}, Sleep: ${user.sleepSchedule})`);
    });
    
    await mongoose.connection.close();
  } catch (error) {
    console.error('❌ Error:', error.message);
  }
}

// Run appropriate function based on command line args
if (require.main === module) {
  const args = process.argv.slice(2);
  if (args.includes('--quick')) {
    quickCheck();
  } else {
    checkMongoData();
  }
}

module.exports = { checkMongoData, quickCheck };
